# Generated by Django 4.1.2 on 2022-10-19 04:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0003_answer_author"),
    ]

    operations = [
        migrations.RenameModel('Question', 'ClassRoom'),
        migrations.RenameModel('Answer', 'Comment'),
    ]
