# Generated by Django 4.1.2 on 2022-10-19 05:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0004_auto_20221019_0426"),
    ]

    operations = [
        migrations.RenameField('Comment', 'question', 'classroom')
    ]
