# Generated by Django 4.1.2 on 2022-10-26 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0006_classroom_modify_date_comment_modify_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="classroom",
            name="container_cnt",
            field=models.CharField(max_length=10),
        ),
        migrations.AddField(
            model_name="classroom",
            name="docker_image",
            field=models.CharField(max_length=100),
        ),
    ]
