# Generated by Django 4.1.2 on 2022-11-05 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0010_classes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="classes",
            name="learners",
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
