# Generated by Django 4.1.2 on 2022-11-05 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0011_alter_classes_learners"),
    ]

    operations = [
        migrations.AddField(
            model_name="classes", name="code", field=models.IntegerField(default=0),
        ),
    ]
