# Generated by Django 4.1.2 on 2022-11-06 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0013_classes_create_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="classes",
            name="learners_num",
            field=models.IntegerField(default=0),
        ),
    ]
