# Generated by Django 4.1.2 on 2022-11-08 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0014_classes_learners_num"),
    ]

    operations = [
        migrations.AddField(
            model_name="classroom",
            name="class_code",
            field=models.IntegerField(default=0),
        ),
    ]
