# Generated by Django 4.1.2 on 2022-11-28 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0015_classroom_class_code"),
    ]

    operations = [
        migrations.RemoveField(model_name="classroom", name="container_cnt",),
    ]
